name: riverpod_infinite_scroll_page
description: "This project is a sample Flutter application demonstrating infinite scrolling pagination using Riverpod for state management. It builds on the infinite_scroll_pagination package and includes optimizations to avoid unnecessary rebuilds. Specifically, it prevents the entire list from being rebuilt when only specific items need updating, resulting in improved performance for large lists."
version: 0.0.4
homepage: https://github.com/lhjandroid/riverpod_infinite_scroll_page

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 2.6.1
  flutter_staggered_grid_view: 0.7.0
  sliver_tools: 0.2.12
  tuple: 2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  
